config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :clients, only: [:index]
  resources :materials, only: [:destroy]
  resources :users do
    resources :projects
    get '/longest_project', to: 'projects#longest_project'
  end
  resources :projects
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/auth/facebook/callback', to: 'sessions#create_from_facebook'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :projects
  has_many :users, through: :projects
  validates_presence_of :name, :email 
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :project
  validates_presence_of :name, :quantity, :price
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  belongs_to :client
  has_many :materials
  has_many :subcontractors
  accepts_nested_attributes_for :client, reject_if: :all_blank
  accepts_nested_attributes_for :subcontractors, reject_if: :all_blank
  accepts_nested_attributes_for :materials, reject_if: :all_blank
  validates_presence_of :name, :length
  scope :longest_project, -> { where("length = ?", self.maximum(:length)) }

  def materials_attributes=(material_attributes)
    material_attributes.values.each do |material_attribute|
      if self.materials.find_by(name: material_attribute[:name])
        material = self.materials.find_by(name: material_attribute[:name])
        material.update(material_attribute)
      else
        if !material_attribute.values.include?("")
          material = self.materials.create(material_attribute)
        end
      end
    end
  end

  def subcontractors_attributes=(subcontractor_attributes)
    subcontractor_attributes.values.each do |subcontractor_attribute|
      if !subcontractor_attribute.values.include?("")
        if Subcontractor.find_by(name: subcontractor_attribute[:name])
          subcontractor = Subcontractor.find_by(name: subcontractor_attribute[:name])
          if subcontractor.specialty != subcontractor_attribute[:specialty]
            subcontractor = Subcontractor.create(subcontractor_attribute)
            self.subcontractors << subcontractor
          else
            self.subcontractors << subcontractor
          end
        else
          subcontractor = Subcontractor.create(subcontractor_attribute)
          self.subcontractors << subcontractor
        end
      end
    end
  end

  def client_attributes=(client_attributes)
    if Client.find_by(name: client_attributes[:name])
      client = Client.find_by(name: client_attributes[:name])
      if client.email != client_attributes[:email]
        client = Client.create(client_attributes)
        self.client = client
      else
        self.client = client
      end
    else
      client = Client.create(client_attributes)
      self.client = client
    end
  end


end

app/models/subcontractor.rb
class Subcontractor < ApplicationRecord
  belongs_to :project
  validates_presence_of :name, :specialty

  def name_with_specialty
    "#{self.name} - #{self.specialty}"
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :projects
  has_many :clients, through: :projects
  has_many :subcontractors, through: :projects
  has_many :materials, through: :projects
  has_secure_password
  validates :username, presence: true, uniqueness: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?
  helper_method :current_user

  def logged_in?
    true if session[:user_id]
  end

  def current_user
    if logged_in?
      User.find(session[:user_id])
    end
  end

  def require_login
    redirect_to '/login' unless session.include? :user_id
  end

  def user_match
    if params[:user_id]
      redirect_to '/login' unless current_user.id == params[:user_id].to_i
    else
      redirect_to '/login' unless current_user.id == params[:id].to_i
    end
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  def index
    @clients = current_user.clients
  end

end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController

  def new
  end

  def create
  end

  def destroy
    @material = Material.find(params[:id]).destroy
    @project = @material.project
    @user = @project.user
    redirect_to edit_user_project_path(@user, @project)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_login
  before_action :user_match
  skip_before_action :user_match, only: [:destroy, :update]

  def index
  end

  def new
    @user = User.find(params[:user_id])
    @project = @user.projects.new
  end

  def create
    @user = User.find(params[:user_id])
    @project = @user.projects.build(project_params)
    if @project.save
      redirect_to user_project_path(@user, @project)
    else
      render :new
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @user = User.find(params[:user_id])
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to user_project_path(@project.user, @project)
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @user = @project.user
    @project.destroy
    redirect_to user_path(@user)
  end

  def longest_project
    if !current_user.projects.empty?
      @project = current_user.projects.longest_project.first
      render :show
    else
      redirect_to current_user
    end
  end

  private

  def project_params
    params.require(:project).permit(:name, :category, :length, subcontractor_ids:[], client_attributes: [:name, :email], subcontractors_attributes: [:name, :specialty],
    materials_attributes: [:name, :price, :quantity])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if logged_in?
      redirect_to current_user
    end 
  end

  def create
    if User.find_by(username: params[:username])
      @user = User.find_by(username: params[:username])
      @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:notice] = "Incorrect username or password"
      redirect_to '/login'
    end
  end

  def create_from_facebook
    @user = User.find_or_create_by(username: auth['info']['email']) do |u|
      if !u.password
        u.password = SecureRandom.hex(8)
      end
    end
    session[:user_id] = @user.id
    redirect_to @user
  end

  def destroy
    session.delete :user_id
    redirect_to '/'
  end

  private

  def auth
    request.env['omniauth.auth']
  end

end

app/controllers/subcontractors_controller.rb
class SubcontractorsController < ApplicationController

  def new
  end

  def create
  end

  def show
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:show]
  before_action :user_match, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    if logged_in?
      redirect_to current_user
    end 
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subcontractors_helper.rb
module SubcontractorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clients/index.html.erb
<ul>
  <% current_user.projects.each do |p| %>
    <li><%= "#{p.client.name} - #{p.name} - #{p.client.email}" %>
  <% end %>
</ul>

app/views/projects/_client_info.html.erb
<li><%= client_fields.label :name, "Client Name" %><br>
<%= client_fields.text_field :name %></li>
<li><%= client_fields.label :email %><br>
<%= client_fields.text_field :email %></li>

app/views/projects/_form.html.erb
</ul>
<%= f.label :category %><br>
<%= f.select(:category, ['Residential', 'Commercial'], include_blank: true) %><br>
<br>
<%= f.label :length, "Weeks for Completion" %><br>
<%= f.text_field :length %><br>
<br>
<%= f.label :subcontractor_ids, "Choose Subcontractors" %><br>
<%= f.collection_check_boxes :subcontractor_ids, Subcontractor.all, :id, :name_with_specialty, include_blank: true %><br>
Add a New Subcontractor:
<ul>
<%= f.fields_for :subcontractors, @project.subcontractors.build do |subcontractors_fields| %>
  <li><%= subcontractors_fields.label :name %><br>
  <%= subcontractors_fields.text_field :name %></li>
  <li><%= subcontractors_fields.label :specialty %><br>
  <%= subcontractors_fields.text_field :specialty %></li>
<% end %>
</ul>

app/views/projects/edit.html.erb
<% if @project.errors.any? %>
  <% @project.errors.full_messages.each do |message| %>
  <p style="color:#ff0000; font-weight:bold"><%= message %></p>
  <% end %>
<% end %>
<h1>Update <%= @project.name %>:</h1>
<%= form_for [@user, @project] do |f| %>
  <%= f.label :name, "Project Name" %><br>
  <%= f.text_field :name %><br>
  <br>
  Client Info:
  <ul>
  <%= f.fields_for :client, @project.client do |client_fields| %>
    <%= render partial: "client_info", locals: {client_fields: client_fields} %>
  <% end %>
  <%= render partial: "form", locals: {f: f} %>
    <% if !@project.materials.empty? %>
    Edit Materials:
    <ul>
      <%= f.fields_for :materials, @project.materials do |materials_fields| %>
      <li><%= materials_fields.label :name %><br>
        <%= materials_fields.text_field :name %><br>
        <%= materials_fields.label :price, "Price Per Unit" %><br>
        <%= materials_fields.text_field :price %><br>
        <%= materials_fields.label :quantity %><br>
        <%= materials_fields.text_field :quantity %></li>
        <%= link_to "Remove", materials_fields.object, method: :delete %>
        <br>
        <% end %>
      </ul>
    <% end %>
  <%= f.submit %>
<% end %>

app/views/projects/new.html.erb
<% if @project.errors.any? %>
  <% @project.errors.full_messages.each do |message| %>
  <p style="color:#ff0000; font-weight:bold"><%= message %></p>
  <% end %>
<% end %>
<h1>Create a New Project:</h1>
<%= form_for [@user, @project] do |f| %>
  <%= f.label :name, "Project Name" %><br>
  <%= f.text_field :name %><br>
  <br>
  Client Info:
  <ul>
  <%= f.fields_for :client, @project.build_client do |client_fields| %>
    <%= render partial: "client_info", locals: {client_fields: client_fields} %>
  <% end %>
  <%= render partial: "form", locals: {f: f} %>
  <%= f.submit %>
<% end %>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>
Type: <%= @project.category %><br>
Estimated Duration: <%= @project.length %> weeks<br>
Subcontractors:
<ul>
<% @project.subcontractors.each do |s| %>
  <li><%= "#{s.name} - #{s.specialty}" %></li>
<% end %>
</ul>
Client Info:
<ul>
  <li>Name: <%= @project.client.name %>
  <li>Email: <%= @project.client.email %>
</ul>
<h3>Required Materials:</h3>
<ul>
<% @project.materials.each do |m| %>
  <li><%= m.name %><br>
    Price Per Unit: $<%= m.price %><br>
    Quantity: <%= m.quantity %></li>
<% end %>
</ul>
Add New Material:
<%= form_for @project do |f| %>
<ul>
<%= f.fields_for :materials, @project.materials.build do |materials_fields| %>
  <li><%= materials_fields.label :name %><br>
  <%= materials_fields.text_field :name %></li>
  <li><%= materials_fields.label :price, "Price Per Unit" %><br>
  <%= materials_fields.text_field :price %></li>
  <li><%= materials_fields.label :quantity %><br>
  <%= materials_fields.text_field :quantity %></li>
<% end %>
</ul>
<%= f.submit "Add to List" %>
<% end %>
<br>
<%= link_to "Edit Project Details", edit_user_project_path(@project.user, @project) %><br>
<%= link_to "Delete Project", @project, method: :delete %>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |message| %>
  <p style="color:#ff0000; font-weight:bold"><%= message %></p>
  <% end %>
<% end %>
<br>
<%= form_for @user do |f| %>
  <%= f.label :username, "Create Username:" %><br>
  <%= f.text_field :username %><br>
  <br>
  <%= f.label :password, "Create Password:" %><br>
  <%= f.password_field :password %><br>
  <br>
  <%= f.label :password_confirmation, "Confirm Password:" %><br>
  <%= f.password_field :password_confirmation %><br>
  <br>
  <%= f.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome, <%= @user.username %>!</h1>
Current Projects:
<ul>
  <% @user.projects.each do |p| %>
    <li><%= link_to p.name, user_project_path(@user, p) %>
  <% end %>
</ul>
<% if !@user.projects.empty? %>
  <%= link_to "View Longest Project", user_longest_project_path(@user) %><br>
<% end %>
<%= link_to "Add a New Project", new_user_project_path(@user) %><br>
<% if !@user.clients.empty? %>
  <%= link_to "View Client List", clients_path %>
<% end %>
<br>

app/views/welcome/index.html.erb
<h1>Welcome to the Construction Project Manager</h1>
<%= link_to "Sign Up", new_user_path %> or <%= link_to "Log In", login_path %><br>
<br>
<%= link_to "Log in with Facebook", '/auth/facebook', method: :post %>